/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.cloud.nativ.networkelements.messages.entities;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Connection extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -7685266850770063006L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Connection\",\"namespace\":\"com.cloud.nativ.networkelements.messages.entities\",\"fields\":[{\"name\":\"ipAddress\",\"type\":\"string\"},{\"name\":\"cost\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Connection> ENCODER =
      new BinaryMessageEncoder<Connection>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Connection> DECODER =
      new BinaryMessageDecoder<Connection>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Connection> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Connection> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Connection> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Connection>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Connection to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Connection from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Connection instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Connection fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence ipAddress;
  private int cost;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Connection() {}

  /**
   * All-args constructor.
   * @param ipAddress The new value for ipAddress
   * @param cost The new value for cost
   */
  public Connection(java.lang.CharSequence ipAddress, java.lang.Integer cost) {
    this.ipAddress = ipAddress;
    this.cost = cost;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return ipAddress;
    case 1: return cost;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: ipAddress = (java.lang.CharSequence)value$; break;
    case 1: cost = (java.lang.Integer)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'ipAddress' field.
   * @return The value of the 'ipAddress' field.
   */
  public java.lang.CharSequence getIpAddress() {
    return ipAddress;
  }


  /**
   * Sets the value of the 'ipAddress' field.
   * @param value the value to set.
   */
  public void setIpAddress(java.lang.CharSequence value) {
    this.ipAddress = value;
  }

  /**
   * Gets the value of the 'cost' field.
   * @return The value of the 'cost' field.
   */
  public int getCost() {
    return cost;
  }


  /**
   * Sets the value of the 'cost' field.
   * @param value the value to set.
   */
  public void setCost(int value) {
    this.cost = value;
  }

  /**
   * Creates a new Connection RecordBuilder.
   * @return A new Connection RecordBuilder
   */
  public static com.cloud.nativ.networkelements.messages.entities.Connection.Builder newBuilder() {
    return new com.cloud.nativ.networkelements.messages.entities.Connection.Builder();
  }

  /**
   * Creates a new Connection RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Connection RecordBuilder
   */
  public static com.cloud.nativ.networkelements.messages.entities.Connection.Builder newBuilder(com.cloud.nativ.networkelements.messages.entities.Connection.Builder other) {
    if (other == null) {
      return new com.cloud.nativ.networkelements.messages.entities.Connection.Builder();
    } else {
      return new com.cloud.nativ.networkelements.messages.entities.Connection.Builder(other);
    }
  }

  /**
   * Creates a new Connection RecordBuilder by copying an existing Connection instance.
   * @param other The existing instance to copy.
   * @return A new Connection RecordBuilder
   */
  public static com.cloud.nativ.networkelements.messages.entities.Connection.Builder newBuilder(com.cloud.nativ.networkelements.messages.entities.Connection other) {
    if (other == null) {
      return new com.cloud.nativ.networkelements.messages.entities.Connection.Builder();
    } else {
      return new com.cloud.nativ.networkelements.messages.entities.Connection.Builder(other);
    }
  }

  /**
   * RecordBuilder for Connection instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Connection>
    implements org.apache.avro.data.RecordBuilder<Connection> {

    private java.lang.CharSequence ipAddress;
    private int cost;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.cloud.nativ.networkelements.messages.entities.Connection.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[0].schema(), other.ipAddress);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.cost)) {
        this.cost = data().deepCopy(fields()[1].schema(), other.cost);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing Connection instance
     * @param other The existing instance to copy.
     */
    private Builder(com.cloud.nativ.networkelements.messages.entities.Connection other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.ipAddress)) {
        this.ipAddress = data().deepCopy(fields()[0].schema(), other.ipAddress);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.cost)) {
        this.cost = data().deepCopy(fields()[1].schema(), other.cost);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'ipAddress' field.
      * @return The value.
      */
    public java.lang.CharSequence getIpAddress() {
      return ipAddress;
    }


    /**
      * Sets the value of the 'ipAddress' field.
      * @param value The value of 'ipAddress'.
      * @return This builder.
      */
    public com.cloud.nativ.networkelements.messages.entities.Connection.Builder setIpAddress(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.ipAddress = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'ipAddress' field has been set.
      * @return True if the 'ipAddress' field has been set, false otherwise.
      */
    public boolean hasIpAddress() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'ipAddress' field.
      * @return This builder.
      */
    public com.cloud.nativ.networkelements.messages.entities.Connection.Builder clearIpAddress() {
      ipAddress = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'cost' field.
      * @return The value.
      */
    public int getCost() {
      return cost;
    }


    /**
      * Sets the value of the 'cost' field.
      * @param value The value of 'cost'.
      * @return This builder.
      */
    public com.cloud.nativ.networkelements.messages.entities.Connection.Builder setCost(int value) {
      validate(fields()[1], value);
      this.cost = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'cost' field has been set.
      * @return True if the 'cost' field has been set, false otherwise.
      */
    public boolean hasCost() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'cost' field.
      * @return This builder.
      */
    public com.cloud.nativ.networkelements.messages.entities.Connection.Builder clearCost() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Connection build() {
      try {
        Connection record = new Connection();
        record.ipAddress = fieldSetFlags()[0] ? this.ipAddress : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.cost = fieldSetFlags()[1] ? this.cost : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Connection>
    WRITER$ = (org.apache.avro.io.DatumWriter<Connection>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Connection>
    READER$ = (org.apache.avro.io.DatumReader<Connection>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.ipAddress);

    out.writeInt(this.cost);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.ipAddress = in.readString(this.ipAddress instanceof Utf8 ? (Utf8)this.ipAddress : null);

      this.cost = in.readInt();

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.ipAddress = in.readString(this.ipAddress instanceof Utf8 ? (Utf8)this.ipAddress : null);
          break;

        case 1:
          this.cost = in.readInt();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










